### ISSUE TITLE
could not get ganglionhub running on win32

### ISSUE THREAD

**Issue by ChrisVeigl** [OpenBCI/OpenBCI_Ganglion_Electron#16]
the official download of openBCI GUI for windows 32 bit (e.g. atom-based tablets) does not include the ganglionHub. I tried to build with npm as suggested - which succeeded. 
i could also create the installer and the "cat" icon shows up in the system tray when I start ganglionhub.exe. 
however, no connection with the ganglion is possible (501 is sent back after connection request). 

has somebody succeeded in connection to the device via CSR dongle / zadig driver replacement on win32 operating systems ?

**Comment by aj-ptw** [comment]
The hub is in the releases section on this repository. You can also download the GUI here with ganglion hub inside. https://github.com/OpenBCI/OpenBCI_GUI/releases/tag/2.2.1-rc.1

**Comment by ChrisVeigl** [comment]
thank you very much, AJ !

this version of the GanglionHub works on my tablet :-)

do you have any idea why the version which I built from the github sources
fails to connect ?

it would be good to replace the 32-bit download on the official openBCI
site with the one containing the GanglionHub

best regards,
chris


2017-07-20 8:12 GMT+02:00 AJ Keller <notifications@github.com>:
